### ISSUE TITLE
Läuft seit 5 Tagen

### ISSUE THREAD

**Issue by KuhnDaniel** [beabel/radiowecker#12]
Ein grosses Dankeschön. Wirklich sehr schön gemacht und funktioniert 1A!

Beste digitale Grüsse aus der Schweiz
Daniel

**Comment by beabel** [comment]
Hallo Daniel,
es freut mich das es läuft und du mit den Anpassungen zufrieden bist.
Aber bitte für so etwas die [Diskussions-Funktion](https://github.com/beabel/radiowecker/discussions) nutzen und nicht Issues. 

Grüße zurück Sachsen
