### ISSUE TITLE
Sleep Funktion im Webinterface Button fehlerhaft

### ISSUE THREAD

**Issue by KuhnDaniel** [beabel/radiowecker#19]
Hallo Beabel
aktiviere ich die Sleepfunktion ist danach der Button im Webinterface weg.
Also kein Ausschalten/Deaktivieren nach Aktivierung der Weckfunktion möglich!?
Auch über das Display Touch geht die deaktivierung des Sleepmodus nicht.
Nur ein Neustart des Radios setzt es zurück.

Müsste ja wie bei der Weckerfunktion sein, denke ich.
Nutze die aktuellste Version!

Beste digitale Grüsse Daniel

**Comment by beabel** [comment]
ja, sobald er aktiviert ist ist der Button "ausgeblendet" ein ausschalten war auch in der AZ-Delivery Version nicht möglich.
Ich habe es so angepasst, das sobald man das Radio einmal stoppt ist auch der Sleep wieder aus.
Denn es hat mich gestört, das der Timer wenn er einmal gestartet war und runterläuft er beim nächsten Start des Radios bereits ein wenig abgelaufen ist.
Jetzt startet er immer mit der eingestellten Zeit.
Ich werde wohl auch noch integrieren, das der Sleep Timer ab einer bestimmten Zeit automatisch aktiviert wird, da mein kurzer den immer vergisst einzuschalten, und ich das dann immer tun muss.

**Comment by KuhnDaniel** [comment]
Ja so macht das Sinn. Hatte es nicht verstanden, wie genau es funktionieren sollte :-)
Erledigt... Danke
