### ISSUE TITLE
Stationsliste, neue Sender einpflegen!?

### ISSUE THREAD

**Issue by KuhnDaniel** [beabel/radiowecker#23]
Hallo in die Runde,

bei der Senderliste, wenn ich diese ergänzen möchte durch eigene Einträge, habe ich auch nach einem Neustart die Liste nicht wirklich zur Verfügung. Ein Weiterschalten - zwischen den Sendern wechseln - ist nicht mehr möglich? Es ist immer nur die erste Station aktiv.

Testen kann ich die Streams, funktionieren auch!

Ist es nur bei mir so? 

Beste digitale Sonntagsgrüsse
Daniel

**Comment by beabel** [comment]
Hallo, also ich kann von der Webseite Einträge ändern, aktivieren etc. und ich kann auch alle umschalten.
OK, die nicht aktiven "blättert" es auch durch, jedoch funktioniert es.
Du hast geschrieben "Sender wechseln - ist nicht mehr möglich" was heißt "nicht mehr" ? nach welchem Vorgang geht es nicht mehr? wobei dem wechseln es ziemlich egal ist, was in der Liste steht. es blättert einmal im Kreis. je nachdem was die MAX_STATION Anzahl ist.

**Comment by KuhnDaniel** [comment]
Nach einer Anpassung eines Senderplatzes - zurück im Radiomodus - lassen sich keine Senderwechsel mehr machen.
Aber gut, es muss ja eh ein Neustart erfolgen, damit die neuen Senderdaten funktionieren. Das habe ich jetzt so verstanden und funktioniert auch tatsächlich.

Ich finde die Sache mit der Senderliste aber eh etwas schwierig. Zumal das ganze ja "flüchtig" im RAM ist. Eine Speicherung als echte Liste wäre optimal. Ich schau mir das ganze jetzt mal im Code an.
